---
title: "neuralnetworkv3"
output: html_document
---

```{r}
# read the data
setwd(dir ="~/datasets/OnlineNewsPopularity")
newsdata=read.csv("NormalizedPCA.csv")[,2:22]
newsdata<-newsdata[complete.cases(newsdata),]
newsdata<-na.omit(newsdata)
```

## Outliers
```{r}
# remove outliers

# out_index = c(2,3,4,5,6,7,8,9,18,19,20,21,23,25,26,27,28,29,59)
# out_index = 59

# individual plots, input index
box_out <- function(x){
  boxplot(newsdata[,x], horizontal = T, names=x)  
}

#input names
box_out_2 <- function(x){
  boxplot(newsdata[x], horizontal = T, names=x )  
}

# lapply(out_index, box_out)
# lapply(names(newsdata)[out_index], box_out_2)


rm_out <- function(x){
  outt = boxplot.stats(newsdata[,x])
  newsdata <<- subset(newsdata, newsdata[,x] <= outt[["stats"]][5])
}

boxplot(newsdata[, out_index], horizontal = T)
lapply(out_index, rm_out)
boxplot(newsdata[, out_index], horizontal = T)
summary(newsdata)
hist(newsdata$shares)

```

## Scaling
```{r}
# min max normalisation
maxs = apply(newsdata, 2, max)
mins = apply(newsdata, 2 ,min)
shares = as.numeric(newsdata$shares)
trainNN <- as.data.frame(scale(newsdata, center = mins, scale = maxs - mins))
# trainNN <- cbind(trainNN, shares)
# scaled = cbind(trainNN[,3:61])
head(trainNN)

testNN = read.csv("NormalizedPCA_test.csv")[,2:22]

#fit
features<-names(trainNN[,2:21])
f <- paste(features,collapse = ' + ')
f <- paste('shares ~', f)
f <- as.formula(f)
```
## Neural Network
```{r}
library(neuralnet)
nn <- neuralnet(f, trainNN, hidden=c(10,10,10), linear.output=T)
# plot(nn)
predicted <- compute( nn, testNN[2:21])
predicted = (predicted$net.result * (max(newsdata$shares) - min(newsdata$shares))) + min(newsdata$shares)
plot(testNN$shares, predicted, col='blue', pch=16, ylab="predicted shares", xlab="real shares")

# abline(0,1)

RMSE = (sum((testNN$shares - predicted)^2) / nrow(testNN)) ^ 0.5
```

## RBF
```{r}
library("RSNNS")
rbfn <- RSNNS::rbf(trainNN[2:21], trainNN[1], size=50, linOut=TRUE)
summary(rbfn)
rbf.predict = predict(rbfn, testNN[2:21])
predicted_rbf = (rbf.predict * (max(newsdata$shares) - min(newsdata$shares))) + min(newsdata$shares)
plot(testNN$shares, predicted_rbf, col='blue', pch=16, ylab="predicted shares", xlab="real shares")
```

